### ISSUE TITLE
Ponomar Unicode. Formation of dynamic diacritics Titlo /uniFE2E/uniFE2F/uniFE26

### ISSUE THREAD

**Issue by StefanPeev** [typiconman/fonts-cu#75] opened 2024-03-21 02:26 UTC
The next step in the development of the project Ponomar Unicode is the realization of a dynamically formed diacritic Titlo for writing numbers. The dynamic Titlo diacritic is formed by the combination of:

alphanumeric character + /uniFE2E + /uniFE2F + alphanumeric character + /uniFE26

which connect to each other with suitably positioned anchors.

The result can be seen in the pictures below.

![Screenshot 2024-03-21 041959](https://github.com/StefanPeev/fonts-cu/assets/12949369/c0f2b3fe-b986-4199-a85c-f6dfc2128f20)

![Screenshot 2024-03-21 043557](https://github.com/StefanPeev/fonts-cu/assets/12949369/51424651-52e2-4b30-aeef-c043c8dfe40e)

See issue [#2](https://github.com/StefanPeev/fonts-cu/issues/2) at my fork.

**Comment by typiconman** [comment] 2024-03-21 07:59
That's impressive, however the correct character sequence should be 
alphanumeric character + /uniFE2E + alphanumeric character + /uniFE2F
for two lettered abbreviations or
alphanumeric character + /uniFE2E + alphanumeric character + /uniFE26 + alphanumeric character + /uniFE2F
for three lettered abbreviations.

**Comment by typiconman** [comment] 2024-03-21 07:59
Also, this is a duplicate of #3.

**Comment by typiconman** [comment] 2024-03-21 08:00
duplicate

**Closed by typiconman** 2024-03-21 08:00 UTC
Labels: duplicate
