### ISSUE TITLE
Add Round Omega as style alternative in Monomakh

### ISSUE THREAD

**Issue by aleslavista** [typiconman/fonts-cu#39] opened 2018-02-23 13:25 UTC
Hello,

As I said in the previous post, I though it better to open a new thread to make it clear we're not debating any longer whether Capital OMEGA should have serifs or not.

Here I intend to argue in favor of giving Monomakh's Capital OMEGA a Rounded Shape, as can be seen on Jagic's transliteration of Codex Marianus and in a font, Dilyana, that looks strikingly similar to the one Jagic selected for his work. Since as you said Monomakh is more of a "generic-purpose" font whose goal is to "look pretty", a rounded OMEGA both looks pretty and also has a history behind it. See attachments.
![omega in dilyana](https://user-images.githubusercontent.com/33322424/36596255-51deec22-18a5-11e8-96d7-63401ce818bb.png)
![round omega jagic](https://user-images.githubusercontent.com/33322424/36596256-5233e1b4-18a5-11e8-89e9-89d8968f5627.png)

**Comment by typiconman** [comment] 2018-02-23 16:47
I am in favor of supporting both forms, which can be done via Stylistic Alternatives. The only question is which form should be the default.

**Comment by aleslavista** [comment] 2018-02-23 18:37
Frankly speaking only LATEX-savy users can make use of such stuff (LO doesn't support this nor, as far as I know, does Office). My selfish proposal is to have a rounded shape by default because, since you pronounced Menaion not fit for a publication, at least I can have Monomakh look like Jagic's font. :)

**Comment by typiconman** [comment] 2018-02-26 12:39
@aleslavista Stylistic Alternatives are supported in LO (see the font documentation) and probably in MS Office as well, though I have no ability to test Microsoft products.

**Comment by aleslavista** [comment] 2018-02-26 15:18
OK, thanks for the information but I'd still vote in favor of making the rounded shape default. Let's be practical-minded: most people only use what works "out of the box", if you implement something as OpenType very few people will be aware of it, let alone make use of it.

As a side note I realized many "casual" Cyrillic fonts like Ubuntu or DejaVu Serif do feature the rounded shape, but I don't know whether this is relevant so I refrained from posting images here because they're not designed with Church Slavonic in mind.

**Comment by aleslavista** [comment] 2018-02-26 15:38
OK, this is my last attempt to win you over to my win you over to my side: letter FERT and THITA have different capital shapes in Monomakh and Ponomar (while lower case looks alike), giving capital OMEGA a rounded shape would give Monomakh more consistency as the internal trend of the font if for the upper case to feature a different shape than the lower case while in Ponomar they tend to look similar. Also it looks cooler :) 
![fert and thita](https://user-images.githubusercontent.com/33322424/36679343-45c8288e-1b13-11e8-8630-9b78f834f1c3.png)

**Comment by starover77** [comment] 2018-02-26 17:31
I have been trying to stay away from this discussion, but I feel compelled to point out that the rounded upper case form is a late innovation to typography. It first started appearing in Kievan publications around 1700 and is an "interloper" if you consider typographic tradition. Since your project is a transliteration from Glagolitic to Cyrillic, why would it be preferable to use a font that complies with features of Kievan-regional typography?

**Comment by aleslavista** [comment] 2018-02-26 17:44
Yes, thanks for your remark, you already pointed that out in the other topic and I absolutely don't mean to discount that. But please mind as well that you've also discouraged me from using the full-fledged USTAV font, Menaion. 

The most compelling rationale for wanting such a shape is that as you can see above, so did Jagic. Also, it seems to me this shape is more widespread in non "technical" fonts,  but I know this may not matter for you. However neither is Monomakh strictly a "technical" font.

**Comment by starover77** [comment] 2018-02-26 20:30
OK, I have another idea. There is a font called "Shafarik" (probably not the original name), which was used extensively from the early 1800s until 1917 in many academic books, and it was specifically designed to reproduce OLD Church Slavic or Paleoslavic texts. As far as I can tell, it was never used to typeset Church Slavonic texts. You can find countless examples of its usage, but perhaps the easiest to recognize is the Slovar' by Diachenko. He used the Shafarik font for Old Church Slavic words, a modern-style Slavonic font for Church Slavonic words, and the civil script (in bold text) for archaic Russian words. I think that this makes an excellent font for academic work, because it is clear and easy to read, and it is does not use many serifs. (It also can be used on the same page with modern Cyrillic and Latin texts, and not create a bizarre visual contrast.)

Back in 2014 I started to adapt this font for Unicode, and I assembled most of the necessary characters, but I was pulled away from the project and it was never completed. The remaining work that needs to be done is to add the attachments points for diacritical marks and to add the "lookup" coding to make the diacriticals attach properly. You may download the working version of the font from here:
http://churchslavonic.net/research/temp/CyrillicaShafarik-Normal.ttf
I invite you to test it and see if it will meet your needs. I realize that the diacritics currently need work, but if you only need superscript and abbreviation characters, but no accents, then we could quickly produce a font that will meet the needs of your project.

BTW: I quickly added the basic Glagolitic characters from another font, including superscript letters, but I am not sure that the characters have proportions which match the Kirilitsa. I did not add the alternate Glagolitic character shapes and the ligatures, but these can be added later, if the font meets your needs. I added Glagolitc because there might be some words that you would want to explain in footnotes. Ideally, I would like to add a basic set of Greek characters as well, to make this font a bit more useful as an academic font.

**Comment by aleslavista** [comment] 2018-02-27 15:25
Thanks, the font looks great. It's very similar to another font I'd have loved to use in my publication, Dilyana, but unfortunately it doesn't feature superscripts.

Still, I don't need just superscripts but also the rough breathing and the circumflex accent, these are not widespread yet seldom used. On the other hand, acute and grave accents, and the smooth breathing are not needed.

However I'd still love to have Monomakh adopt the round OMEGA as default, please do examine also the shape of capital THITA in Monomakh: isn't that too an interloper? It's a distinctively modern look that appears also on non CS fonts alongside round OMEGA.

**Comment by aleslavista** [comment] 2018-02-27 16:35
On top of that, I also need titlo and pokrytie.

Of course adding Greek and Glagolitic would make of it a superb font, unfortunately I've been discouraged by my publisher from typesetting in Glagolitic, I felt Jagic made a mistake to use transliteration but my publisher did have a point when he retorted it'd fatally restrict the readership.

**Comment by starover77** [comment] 2018-02-28 01:00
If you are serious in using the Shafarik font, I can prepare a working version that will meet any of your needs. As you work with it, send me a list of what you need, what is missing or doesn't yet work right, and I can make the necessary changes and send you an improved copy. I can do this as many times as you need, so that we can help you complete your project.

As for the Glagolitic script, I do sympathize with you, but I have to agree with your publisher about producing a book which your readers can read. However, in the front of the book, you will need to inform your readers that you are transliterating the text out of necessity, and you will <ideally and logically> need to typeset a table of characters to demonstrate how the Glagolitic characters translate to Cyrillic characters. Perhaps add a few images to demonstrate what the original text looks like. This is just standard procedure when issuing an academic translation or transliteration.

**Comment by aleslavista** [comment] 2018-02-28 11:35
Yes, I'm really willing to use Shafarik, please do send me a working version at: aleslavista@yahoo.com so I'll let you know if there's something still lacking or a bug in the design.

About the original text, please mind that I'm working on Jagic's critical edition, **not** on the original text.  Frankly speaking, I wouldn't even know whether scans of the Codex Marianus manuscript are available.

OK, lastly is my proposal to have round OMEGA as a default definitively rejected? Please disprove the arguments I've brought forward above, if you want I can restate all of them in a post below.

Thank you so much for your precious support.

**Comment by typiconman** [comment] 2018-02-28 11:57
Like I said, I definitely support adding the round Omega to Monomachus. But I'm not sure that it has to be the default form. I think that anyone who needs it would be able to select it via stylistic alternatives (or, if they use software that doesn't support salt, from the PUA).

**Comment by starover77** [comment] 2018-02-28 14:06
@aleslavista - I have already posted a link to the working version of Shafarik, in the post where I mentioned it to you. Download it, install it, test it out, and let me know what modifications you need me to make in order for it to meet all your needs. (It doesn't look like we have to fuss with accents for you to use the font for your project, so that should be one less thing to worry about at the present time.) There are some additional changes I need to make to it in the near future, such as adding the modern shape of the letter cherv as a stylistic alternative, but these changes probably won't affect you.

@typiconman - I completely support your proposal to add the round Omega to Monomachus as a stylistic alternative. --- While we are at the task of adding stylistic alternatives, I suppose we could address the issue of the two shapes of the letter cherv (ch): Old Slavic vs. Church Slavonic, as pictured below. We already have some accommodation for this in the PUA at U+E400 and U+E401, so we could include this in the stylistic alternative set for Ustav fonts.
![2018-02-28 09_00_27-advance width metrics for cyrillicashafarik-normal](https://user-images.githubusercontent.com/10853367/36791442-dd9f691c-1c65-11e8-9807-4d8aefa0a037.png)

**Comment by aleslavista** [comment] 2018-02-28 19:56
@starover77 As a matter of fact I'm already using it but since you told it was a "working" version, I was (mistakenly) awaiting kind of a new version.

![shafarik sample](https://user-images.githubusercontent.com/33322424/36807526-87a86e60-1cc3-11e8-8b8b-9930f98c2672.png)

The most pressing issue is the lack of rough breathing, also the lack of descenders in CHER is startling in a CS font, but this might be more of a subjective judgement.

@typiconman Here's a couple of arguments in favor of round OMEGA as a default shape:

1.  It's way cooler, let's face it :)

2. It bolsters an already existing trend in Monomakh of giving capital letters a different shape than lower cases: see https://github.com/typiconman/fonts-cu/issues/39#issuecomment-368543531 unlike Ponomar which is more conservative in that regard. So this would help prop up the "division of roles" between Ponomar and Monomakh, as the former aims to painstakingly reproduce an existing typeface while the latter is a nice looking general-purpose font.

3. Round OMEGA is the shape implemented in many non-CS fonts and also in some CS like Dilyana, and last but not least Shafarik.

4. Granted, round OMEGA may be an interloper but then an interloper is still better than an aberration, right? And a serified OMEGA definitely is an aberration, as you yourself have ascertained in the other post.

5. Round OMEGA isn't as "marginal" or specific as the archaic shape of CHERV or the modern one of SHTA and so on you mentioned as OpenType alternatives in the user manual, round OMEGA does enjoy a widespread acceptance in the Cyrillic font panorama. Alternatives should be restricted to "niche" stuff. You can't discount this.

6. If you implement something as on OpenType feature few people are going to use it as they wouldn't know of its existence unless they read the user manual, which few people do anyway.

I hope this may suffice to win you over to my side. Of course you're the owner of the font and it's up to you.

**Comment by aleslavista** [comment] 2018-03-25 18:53
Hello, is this thread closed? Because nobody has been posting here for almost a month.

**Comment by typiconman** [comment] 2018-03-26 06:46
It's on the to-do list. I don't know when I'll get to it. Right now the main focus is to get the Znamenny Notation fonts working properly.

**Comment by aleslavista** [comment] 2018-03-26 16:22
OK, thanks. May I ask you what's your stance on https://github.com/typiconman/fonts-cu/issues/39#issuecomment-369363033?

P.S.

I'd like to remind you for some time I've not been receiving notifications. I emailed you about that but apparently you didn't seem to notice it.

**Comment by typiconman** [comment] 2018-03-26 16:25
@aleslavista We'll add the Round Omega. Which form will be the default and which will be accessible as an alternative -- I think we'll decide that when we design the character.

I did receive your email, but I'm not sure what you mean by "not receiving notifications". Do you mean from the GitHub site? There probably have not been any posts in the threads to which you're subscribed.

**Comment by aleslavista** [comment] 2018-03-26 19:34
I'm sorry if I annoyed you, I insisted because at the moment I'm devoid of a font for my project, Monomakh would've been a good choice yet I feel the shape of capital OMEGA to be inappropriate for my needs so that's why I've been lobbying so long for a change.

Also, please let me know if perchance you happen to be interested in what I'm doing I posted a picture above, that should give you an idea of what I'm up to.

Concerning notifications from GitHub, no you did post here twice yet I received no notifications, I also looked into the spam folder, nothing.

**Comment by typiconman** [comment] 2018-03-27 06:47
Well, this is free software, and the developers have only so much time they can devote to it. We try to make it useful to as many people as possible, but we don't always succeed.

If you need something fast, you're always welcome to fork the code and modify it yourself.

**Comment by aleslavista** [comment] 2018-03-27 12:14
Sorry, as I said I didn't mean to annoy you. In fact, I was just wondering whether you could grow interested in what I'm doing, so maybe you'd want to collaborate with me. If you've got other things to do, just forget about it.

As for modifying the code... I don't even know what a code looks like. :( But for the record, I did volunteer to translate the user manual, so it's not that I just want to enjoy a free ride either.

**Comment by starover77** [comment] 2018-03-27 13:00
You are certainly not annoying us, and I am sure that I can speak for Aleksandr when I say that we are certainly interested in your project, but please keep in mind that both Aleksandr and myself are currently very busy with other projects, academic studies, preparation for Pascha (which is approaching far too fast for me this year), family medical issues, etc. We are happy to assist you, but everyone has a lot of competing commitments at this time of the year, and we might have to wait until after Pascha to find the time to assist you properly. (At least I am speaking for myself.)

It seems that you had some interest in using the Shafarik font, but as I mentioned previously, I need you to send me a very clear TO-DO list of what changes you need me to make in order to better serve your needs. Scattered remarks throughout this and other threads doesn't help me, as I don't have the time to track them all down. It would be best to send it directly to my email, and if I need clarification, I can email you back.

Regarding the addition of Round Omega: I support it, but only as a Stylistic Alternative character, not the primary form. If we do add it as such, you can easily add the Round Omega into your documents by opening up your character palette in your Word program and selecting it. (While it is technically best to type the primary character and apply the Stylistic Alternative via a menu, which ensures that your document is searchable, you can substitute the visual character using your character palette to get the job done. Keep in mind that the work-around is not going to give you text which is properly searchable. On the other hand, if you are only preparing this for printing on actual paper, it won't really matter which way you typeset the character.)

**Comment by aleslavista** [comment] 2018-04-04 11:50
@starover77 Interoperability is paramount for me as the text is going to be edited across multiple platforms and nothing guarantees that these platforms are going to support OpenType, so that's why I insisted on capital Round Omega as the primary form. Everything else would be impracticable from my standpoint.

**Comment by starover77** [comment] 2018-04-04 14:51
OpenType was specifically designed to be cross-platform compatible, so this should not be a cause for concern. It works equally well on PC, Mac and Linux (and I'm assuming Android too).
See: https://www.adobe.com/products/type/opentype.html

Regarding Capital Round Omega as a primary form: If you can provide us with images that prove beyond a doubt that Round Omega is the historically correct form of the letter, then we can certainly consider making such a change. But for now, I have only seen evidence that it was an innovation introduced into Kievan Poluustav typography in the late 1600s. Until you can prove to us otherwise, we have no choice but to consider Capital Round Omega as a Stylistic Alternative. I simply do not have any interest in fabricating historical letter forms that are not attested and documentable, so please prove this or let us move on from the topic. Thanks

**Comment by typiconman** [comment] 2019-03-22 13:45
I fixed the appearance of U+A64C in Monomakh and I added the rounded form of Omega as a stylistic alternative to U+0460.
@starover77 Do you support the proposal by @aleslavista to make the round form default? See attached image.

![Screenshot from 2019-03-22 16-42-14](https://user-images.githubusercontent.com/5428695/54826874-d1934700-4cc1-11e9-9a3b-5ae5c0243455.png)

**Comment by starover77** [comment] 2019-03-22 22:37
No, I do not support the proposal to make the round form default. We have discussed this again and again, and I still stand by my original argument, posted on February 26, 2018: "....the rounded upper case form is a late innovation to typography. It first started appearing in Kievan publications around 1700 and is an "interloper" if you consider typographic tradition."

I DO support the proposal to add this to the font as a Stylistic Alternative {salt}, as Aleksandr Andreev demonstrated in the previous post.

If accessing this is a concern, here is how it is done: In LibreOffice (the most up-to-date version!), select the entire word where you wish to apply the alternate character form, and then go to the font box at the top of the page. Put your cursor in the box and add ":salt" (omitting the quotation marks) to the end of the font's name. For instance: MonomakhUnicode:salt. This will change the *appearance* of the Capital Omega, but it will not change its inherent value.

I will add this feature to the Shafarik font in the next few days and make the font available for those who want to work with it.

**Comment by typiconman** [comment] 2019-03-23 10:34
In this case this issue is resolved. I will now close it.

@starover77 Do you want to distribute your Shafarik font as part of issue #47?

**Closed by typiconman** 2019-03-23 10:34 UTC
Labels: enhancement

**Comment by starover77** [comment] 2019-03-23 12:43
Yes, I would like to distribute the font. However, after I add the 'salt' lookup for the Rounded Capital Omega, I would like to have this run through the usual validation procedures and other testing before we publicly release it.
