### ISSUE TITLE
Monomakh: wrong metrics or kerning for cyrillic letter д

### ISSUE THREAD

**Issue by pgmmpk** [typiconman/fonts-cu#20] opened 2017-01-09 00:28 UTC
In some words letter д seem to be shifted right

<img width="196" alt="screen shot 2017-01-08 at 7 26 35 pm" src="https://cloud.githubusercontent.com/assets/569458/21754952/6d8852bc-d5d8-11e6-9cf9-e26827526835.png">

<img width="122" alt="screen shot 2017-01-08 at 7 25 40 pm" src="https://cloud.githubusercontent.com/assets/569458/21754941/4884b6ea-d5d8-11e6-8687-c61538c9f874.png">

**Comment by typiconman** [comment] 2017-01-09 07:35
It looks like the OpenType version of the font is over-kerned in some instances.

**Comment by pgmmpk** [comment] 2017-01-18 00:54
Here is a list of all non-zero kerns in MonomakhUnicode, with matching samples from `cu-tex`'s `words.txt` list.

Words in `words.txt` list were processed as such:
1. accents stripped off
2. Uppercased version of word generated
3. Capitalized version of word generated
4. letter pairs extracted and matched to the font's kern pairs
5. for each kern collected up to 10 words that have such a pair in them

Following kern pairs seem problematic to me:

1. гл
2. гм
3. гє
4. де
5. до
6. дъ
7. дѐ
8. дє
9. дѣ
10. дѵ
11. дꙋ
12. лꙋ
13. юд
14. ѳе
15. ѳо
16. ѳѵ
17. ѳѷ
18. ѳꙋ


[y.pdf](https://github.com/typiconman/fonts-cu/files/712718/y.pdf)

**Comment by starover77** [comment] 2017-01-18 01:30
I have been following this discussion, but so far have had nothing to contribute. I would like to point out that the practice of kerning is completely anachronistic for Church Slavonic scripts, with the possible exception of combinations like "Та, Ги" (and even so, most printed sources I have in my large library do not use any form of kerning). I would sincerely encourage people to avoid using kerning; it is a modern practice that has no authentic use in historical Slavonic typography. To be honest, the example I saw in the demo PDF looks very strange to me.

**Comment by pgmmpk** [comment] 2017-01-18 02:32
Interesting view, thank you @starover77 

As an experiment, here is the same "kern table" but typeset with the font where all kerning has been removed.

Amazingly, many sample look good without any kerning.

That said, MonomakhUnicode font does not attempt to mimic any historic look'n'feel. Quite the opposite -- it has intentionally "modern" look. My guess is that the point is to make it 

1. more familiar and "readable" for today's reader
2. be compatible with latin script

So, some level of kerning may be okay.

[y-nokerns.pdf](https://github.com/typiconman/fonts-cu/files/712888/y-nokerns.pdf)

**Comment by starover77** [comment] 2017-01-18 02:39
The version without kerning looks much better to me.... more organic, legible and flowing. The version with kerning introduces a "tightness" (or a "pinched" quality) that is uncharacteristic of period texts.
- Nikita

**Comment by typiconman** [comment] 2017-01-18 12:00
I believe that this issue is now fixed. Please test, and let me know if there are any further problems.

**Comment by typiconman** [comment] 2017-01-18 12:30
Question: is there a way to automatically update the website once the fonts are build in the fonts repository?

**Comment by typiconman** [comment] 2017-01-18 12:32
@pgmmpk Regarding the kerning: the De pairs are clearly over-kerned and need to be fixed, as are the other pairs you point out.
@starover77 While I understand your opposition to kerning, Monomakh is not an authentic period typeface and does not seek to reproduce one. It should have the accepted kerning features of modern fonts.

**Comment by typiconman** [comment] 2017-01-19 08:12
@pgmmpk Can you test the kerning in your sample files again, please. I reduced the specified kerning for these cases by 50%.

**Comment by typiconman** [comment] 2017-01-19 08:15
@pgmmpk Again GitHub will not let me attach the ZIP, so I will e-mail you the font file. Or you can build from source.

**Comment by pgmmpk** [comment] 2017-01-19 20:12
[MonomakhUnicode.zip](https://github.com/typiconman/fonts-cu/files/717644/MonomakhUnicode.zip)

Just for the reference, attached ZIP with the test font version that @typiconman mentioned above.
[Strangely, I have no problems selecting ZIP files and attaching them, hmm...]

I realized that some kern pairs did not have any samples (e.g. ду), for the simple reason that I was using Church Slavonic words list. So I extended the word list with Russian words by tokenizing vol 2 of "War and Peace".

Attaching the source, so that anyone can build the text document (had to ZIP it to make
GitHub accept it here in comments): 
[kern-text.zip](https://github.com/typiconman/fonts-cu/files/717649/kern-text.zip)

And this is how it looks when built with the latest font from Aleksandr:
[kern-test.pdf](https://github.com/typiconman/fonts-cu/files/717652/kern-test.pdf)

It is much better, but still has some uneven pairs that need attention:

1. га
2. гд
3. гр
4. ду
5. ьс
6. Not so sure, please check: ѵд  Оуд

**Comment by typiconman** [comment] 2017-01-25 10:54
@pgmmpk: I updated the kerning in the cases you mentioned and a few others.

Please see if there are any further issues. I will send you a binary of the font via e-mail shortly.

If there are no further problems, I will then update the SIL Graphite version of the kerning, and then we can mark this as resolved.

**Comment by pgmmpk** [comment] 2017-01-29 22:55
Latest test file is attached.

I see no problems with the latest version of the font. Lets release it.

[kern-test.pdf](https://github.com/typiconman/fonts-cu/files/737883/kern-test.pdf)

**Comment by typiconman** [comment] 2017-01-31 07:37
I updated the kerning in the Graphite version (see 884d2b21954f55aeafa8d75597a6111aca512e37)
I believe this is now fixed. I will build the new distro and send it to you.
Please update the website.

**Closed by typiconman** 2017-01-31 07:37 UTC
Labels: bug
