### ISSUE TITLE
Correct Shape of YEST in OCS

### ISSUE THREAD

**Issue by aleslavista** [typiconman/fonts-cu#41] opened 2018-02-27 15:05 UTC
This is a rather thorny issue, I hope I'm going to be able to sum it up as best as I can.

Should (iotated) EST in Old Church Slavonic resemble a Latin capital E or rather a Greek epsilon? Staroslavjanski Slovar settles for the latter, I guess this is a normative text, so it should weigh to an extent. However Jagic uses in the former shape, also remember that iotated EST doesn't exist in Glagolitic so neither does it appear in transcription.

However in the Synodal Bible things get more complicated as **both** shapes are in use: the latter as a word-initial variant, the former everywhere else. So the epsilon-shaped EST is in the Synodal Bible more or less the functional equivalent of Iotated EST which does **not** occur in it as far as I can see. However the character is nonetheless included in Ponomar and it looks like a iotated version of the Latin capital E-shaped EST. This seems weird to me as I was accustomed to it looking like a iotated epsilon. If you can confirm it's not in use in the Synodal Bible I suggest you strike it out of the glyph inventory as per your policy stated in the documentation of not including glyphs that are not part of the synodal redaction (by the way also Iotated Little Yus and the two Big Yuses don't seem to be in use either).

So the million-dollar question is which glyph is to be used for reproducing/transliterating OCS text (as opposed to Synodal text), in other words, should I use a different glyph for OCS and Synodal CS?

**Comment by typiconman** [comment] 2018-02-28 06:39
I'm confused as to what you're asking.
In terms of the usage of the wide yest є vs. the narrow yest е in Synodal Slavonic, see any standard reference, e.g.: http://www.ponomar.net/files/gama2/p002.htm
Iotated yest does not exist in Synodal Slavonic.

In terms of what's included in fonts, I know there was some talk earlier on in the project (and it may have gotten into UTN 41) that fonts should not include anachronistic glyphs, but I don't agree with that view any longer. Fonts should strive to include as many glyphs as possible. Fonts that have gaps in them are very annoying and lead to all sorts of problems.

**Comment by aleslavista** [comment] 2018-02-28 11:49
Hello,

I was referring to OCS usage, not Synodal Slavonic. To put it in other words, Is wide YEST the letter introduced in early OCS Cyrillic and therefore narrow YEST a later innovation, like for instance the ligatures YERY or UK that belong only to Synodal Slavonic? If so, then iotated YEST in Ponomar should look like a iotated **wide** YEST, if you bother to include it at all, but the real issue is as I said above whether wide YEST **and not narrow YEST** should be the correct shape of YEST in OCS texts. That's how it looks like in both Staroslavyanski Slovar and Lunt's OCS Grammar.

As far as anachronistic glyphs are concerned, the whole [Typometar font series](http://www.tipometar.org/tipometar/Fontovi.html) **only includes Serbian letters**, even to the exclusion of Russian ones, like YA (the one that looks like an inverted R), YU, the YERS, and so on, and I've never met any trouble in using it. Since these fonts are focused on implementing special Serbian glyphs for letters like б and others, it makes sense for them to avoid non-Serbian letters.

**Comment by aleslavista** [comment] 2018-02-28 19:58
Concerning the omission of characters, as a matter of fact, Shafarik **does omit** some Serbian glyphs which are included by default in basic, Windows 1251-compatible Cyrillic fonts, yet I didn't experience any trouble with it.

**Comment by aleslavista** [comment] 2018-04-04 11:52
@typiconman I'm still waiting for you to answer [this](https://github.com/typiconman/fonts-cu/issues/41#issuecomment-369215850)

**Comment by typiconman** [comment] 2019-03-17 12:06
Since as far as I can tell this is not a bug report, or a feature request, I'm closing the issue.

If there is something you'd like us to fix in the font, please reopen, and be specific.

**Closed by typiconman** 2019-03-17 12:06 UTC
